/**
 * 页面样式注入（幂等），使用 --dsw-alias-* 主题 CSS 变量适配深浅主题。
 *
 * @module @dsh-plugin/disk-sentinel/client/css
 */

/** 注入页面样式（幂等）。 */
function injectCss() {
	var TAG = "disk-sentinel/styles.css";
	if (document.querySelector('style[data-plugin-css="' + TAG + '"]')) return;
	var style = document.createElement("style");
	style.setAttribute("data-plugin", "disk-sentinel");
	style.setAttribute("data-plugin-css", TAG);
	style.textContent = [
		".pcc-panel{position:fixed;top:0;right:0;bottom:0;width:var(--pcc-panel-w,50%);min-width:340px;max-width:92vw;z-index:1000;",
		"background:linear-gradient(180deg,var(--dsw-alias-bg-base,#fff),var(--dsw-alias-bg-layer-1,#f7f8fa));",
		"color:var(--dsw-alias-label-primary,#1f2329);border-left:1px solid var(--dsw-alias-border-l2,#e5e6eb);",
		"box-shadow:-12px 0 32px rgba(17,24,39,.12);display:flex;flex-direction:column;",
		"pointer-events:auto;font-size:13px;line-height:1.55;letter-spacing:0;}",
		".pcc-panel *{box-sizing:border-box;}",
		".pcc-panel-head{display:flex;align-items:center;gap:10px;padding:13px 16px;",
		"background:color-mix(in srgb,var(--dsw-alias-bg-base,#fff) 92%,transparent);",
		"border-bottom:1px solid var(--dsw-alias-border-l2,#e5e6eb);flex:none;backdrop-filter:blur(10px);}",
		".pcc-panel-title{font-size:14px;font-weight:650;margin:0;flex:1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}",
		".pcc-panel-back,.pcc-panel-close{appearance:none;-webkit-appearance:none;width:30px;height:30px;border:0;background:transparent;cursor:pointer;",
		"color:var(--dsw-alias-label-secondary,#4e5969);border-radius:6px;flex:none;display:inline-flex;align-items:center;justify-content:center;padding:0;}",
		".pcc-panel-back{width:28px;height:28px;}",
		".pcc-back-icon{display:inline-flex;align-items:center;justify-content:center;line-height:0;}",
		".pcc-panel-close{font-size:15px;}",
		".pcc-panel-back:hover,.pcc-panel-close:hover{background:var(--dsw-alias-interactive-bg-hover,#e8f3ff);color:var(--dsw-alias-label-primary,#1f2329);}",
		".pcc-panel-body{flex:1;min-height:0;overflow-y:auto;padding:16px 16px 26px;",
		"display:flex;flex-direction:column;gap:14px;scrollbar-gutter:stable;}",
		".pcc-panel-body>div{display:flex;flex-direction:column;gap:10px;}",
		".pcc-section-title{font-size:12px;font-weight:650;margin:6px 0 4px;",
		"color:var(--dsw-alias-label-secondary,#4e5969);letter-spacing:0;}",
		".pcc-desc{font-size:12px;color:var(--dsw-alias-label-tertiary,#86909c);margin:0;}",
		".pcc-hero{border:1px solid var(--dsw-alias-border-l2,#e5e6eb);background:var(--dsw-alias-bg-base,#fff);",
		"border-radius:8px;padding:12px 13px;color:var(--dsw-alias-label-secondary,#4e5969);display:flex;flex-direction:column;gap:4px;}",
		".pcc-btn{appearance:none;-webkit-appearance:none;border:1px solid var(--dsw-alias-border-l2,#e5e6eb);border-radius:8px;",
		"background:var(--dsw-alias-bg-base,#fff);color:inherit;font:inherit;",
		"min-height:34px;padding:7px 13px;cursor:pointer;font-size:13px;transition:background .16s,border-color .16s,box-shadow .16s,transform .16s;}",
		".pcc-btn:hover{background:var(--dsw-alias-interactive-bg-hover,#e8f3ff);border-color:rgba(22,93,255,.25);}",
		".pcc-btn:active{transform:translateY(1px);}",
		".pcc-btn:focus-visible,.pcc-drive:focus-visible,.pcc-tab:focus-visible,.pcc-history-btn:focus-visible,.pcc-panel-back:focus-visible,.pcc-panel-close:focus-visible,.pcc-sidebar-btn:focus-visible{outline:2px solid rgba(22,93,255,.45);outline-offset:2px;}",
		".pcc-btn:disabled{opacity:.55;cursor:not-allowed;transform:none;box-shadow:none;}",
		".pcc-btn-primary{background:var(--dsw-alias-state-business-primary,#165dff);",
		"border-color:var(--dsw-alias-state-business-primary,#165dff);color:#fff;",
		"font-weight:650;box-shadow:0 8px 18px rgba(22,93,255,.18);}",
		".pcc-btn-primary:hover{background:var(--dsw-alias-state-business-primary,#165dff);box-shadow:0 10px 22px rgba(22,93,255,.24);}",
		".pcc-btn-danger{color:#e5484d;border-color:rgba(229,72,77,.35);background:rgba(229,72,77,.04);}",
		".pcc-btn-danger:hover{background:rgba(229,72,77,.08);border-color:rgba(229,72,77,.5);}",
		".pcc-drive{display:grid;grid-template-columns:minmax(86px,max-content) minmax(80px,1fr) minmax(120px,1.4fr);",
		"align-items:center;gap:10px;padding:10px 12px;border-radius:8px;border:1px solid var(--dsw-alias-border-l2,#e5e6eb);",
		"cursor:pointer;margin:0;background:var(--dsw-alias-bg-base,#fff);transition:background .16s,border-color .16s,box-shadow .16s;}",
		".pcc-drive:hover{border-color:rgba(22,93,255,.22);background:var(--dsw-alias-interactive-bg-hover,#e8f3ff);}",
		".pcc-drive[data-selected]{border-color:var(--dsw-alias-state-business-primary,#165dff);",
		"background:rgba(22,93,255,.07);box-shadow:0 0 0 1px rgba(22,93,255,.08) inset;}",
		".pcc-drive-label{font-weight:650;min-width:0;white-space:nowrap;}",
		".pcc-drive-meta{font-size:11px;color:var(--dsw-alias-label-tertiary,#86909c);min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}",
		".pcc-capbar{height:8px;border-radius:999px;overflow:hidden;flex:1;",
		"background:var(--dsw-alias-border-l1,#f2f3f5);display:flex;min-width:64px;}",
		".pcc-capbar-used{background:linear-gradient(90deg,var(--dsw-alias-state-business-primary,#165dff),#22a7f0);height:100%;}",
		".pcc-capbar-free{background:var(--dsw-alias-state-success-primary,#00b42a);height:100%;}",
		".pcc-statrow{display:grid;grid-template-columns:repeat(auto-fit,minmax(110px,1fr));gap:8px;}",
		".pcc-stat{min-width:0;border:1px solid var(--dsw-alias-border-l2,#e5e6eb);",
		"border-radius:8px;padding:10px 11px;background:var(--dsw-alias-bg-base,#fff);}",
		".pcc-stat-value{font-size:17px;font-weight:700;line-height:1.25;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}",
		".pcc-stat-label{font-size:11px;color:var(--dsw-alias-label-tertiary,#86909c);margin-top:2px;}",
		".pcc-drive-stat{border:1px solid var(--dsw-alias-border-l2,#e5e6eb);background:var(--dsw-alias-bg-base,#fff);",
		"border-radius:8px;padding:10px 11px;}",
		".pcc-row{display:grid;grid-template-columns:minmax(0,1fr) max-content;align-items:center;gap:10px;",
		"padding:7px 9px;border-radius:6px;font-size:12px;position:relative;overflow:hidden;margin:0;",
		"border:1px solid transparent;}",
		".pcc-row:hover{background:var(--dsw-alias-interactive-bg-hover,#e8f3ff);border-color:rgba(22,93,255,.12);}",
		".pcc-row-bar{position:absolute;left:0;top:0;bottom:0;",
		"background:var(--dsw-alias-state-business-primary,#165dff);opacity:.075;}",
		".pcc-row-path{min-width:0;overflow:hidden;text-overflow:ellipsis;",
		"white-space:nowrap;position:relative;}",
		".pcc-row-size{font-weight:650;white-space:nowrap;position:relative;}",
		".pcc-progress-card{border:1px solid var(--dsw-alias-border-l2,#e5e6eb);background:var(--dsw-alias-bg-base,#fff);",
		"border-radius:8px;padding:18px 14px;text-align:center;}",
		".pcc-progress-num{font-size:30px;font-weight:750;text-align:center;margin:4px 0 2px;line-height:1.2;}",
		".pcc-progress-path{font-size:11px;color:var(--dsw-alias-label-tertiary,#86909c);",
		"overflow:hidden;text-overflow:ellipsis;white-space:nowrap;text-align:center;",
		"margin:6px 0 0;direction:rtl;}",
		".pcc-pulse{display:inline-block;width:8px;height:8px;border-radius:50%;",
		"background:var(--dsw-alias-state-business-primary,#165dff);margin-right:8px;",
		"animation:pccPulse 1.2s ease-in-out infinite;}",
		"@keyframes pccPulse{0%,100%{opacity:1}50%{opacity:.25}}",
		".pcc-error{color:#e5484d;font-size:12px;padding:8px 10px;border-radius:8px;",
		"background:rgba(229,72,77,.08);border:1px solid rgba(229,72,77,.3);margin:0;}",
		".pcc-sidebar-anchor{display:none!important;}",
		".pcc-sidebar-top-slot{display:inline-flex;align-items:center;justify-content:center;flex:none;margin:0 0 0 auto;}",
		".pcc-sidebar-top-slot+[class*='_searchSlot']{flex:none;margin-left:0;}",
		".pcc-sidebar-top-slot[data-rail]{width:36px;height:36px;margin:0 0 12px;}",
		".pcc-sidebar-btn{appearance:none;-webkit-appearance:none;border:1px solid var(--dsw-alias-border-l1,#f2f3f5);",
		"background:var(--dsw-alias-bg-layer-1,#f7f8fa);",
		"color:var(--dsw-alias-label-primary,#1f2329);border-radius:8px;padding:6px 10px;",
		"font-size:12px;cursor:pointer;white-space:nowrap;display:inline-flex;",
		"align-items:center;justify-content:center;gap:6px;max-width:100%;overflow:hidden;}",
		".pcc-sidebar-btn[data-collapsed]{width:34px;height:34px;padding:0;}",
		".pcc-sidebar-btn[data-top]{width:28px;height:28px;border-color:transparent;background:transparent;border-radius:50%;padding:0;color:var(--dsw-alias-label-secondary,#4e5969);}",
		".pcc-sidebar-btn[data-top][data-collapsed]{width:28px;height:28px;color:var(--dsw-alias-label-secondary,#4e5969);}",
		".pcc-sidebar-top-slot[data-rail] .pcc-sidebar-btn[data-top][data-collapsed]{width:36px;height:36px;color:var(--dsw-alias-label-primary,#1f2329);}",
		".pcc-sidebar-icon{width:18px;height:18px;display:inline-flex;align-items:center;justify-content:center;line-height:0;flex:none;}",
		".pcc-sidebar-icon svg{width:18px;height:18px;display:block;}",
		".pcc-sidebar-label{min-width:0;overflow:hidden;text-overflow:ellipsis;}",
		".pcc-sidebar-caret{flex:none;color:var(--dsw-alias-label-tertiary,#86909c);}",
		".pcc-sidebar-btn[data-active]{border-color:transparent;background:var(--dsw-alias-interactive-bg-hover,#f2f3f5);",
		"color:var(--dsw-alias-label-primary,#1f2329);}",
		".pcc-sidebar-btn[data-top][data-active]{border-color:transparent;background:var(--dsw-alias-interactive-bg-hover,#f2f3f5);}",
		".pcc-sidebar-btn:hover{background:rgba(22,93,255,.08);}",
		".pcc-history-item{display:flex;align-items:center;gap:6px;padding:8px 9px;border-radius:8px;",
		"border:1px solid var(--dsw-alias-border-l2,#e5e6eb);margin:0;background:var(--dsw-alias-bg-base,#fff);font-size:12px;}",
		".pcc-history-item+.pcc-history-item{margin-top:2px;}",
		".pcc-history-meta{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--dsw-alias-label-secondary,#4e5969);}",
		".pcc-history-btn{border:none;background:transparent;cursor:pointer;font-size:12px;padding:4px 7px;",
		"border-radius:6px;color:var(--dsw-alias-state-business-primary,#165dff);white-space:nowrap;}",
		".pcc-history-btn:hover{background:var(--dsw-alias-interactive-bg-hover,#e8f3ff);}",
		".pcc-history-btn[data-danger]{color:#e5484d;}",
		".pcc-plan-content{white-space:pre-wrap;word-break:break-word;font-size:12px;line-height:1.7;",
		"background:var(--dsw-alias-bg-base,#fff);border:1px solid var(--dsw-alias-border-l2,#e5e6eb);",
		"border-radius:8px;padding:12px;margin:0 0 10px;}",
		".pcc-history-item[data-diff-base]{border-color:var(--dsw-alias-state-business-primary,#165dff);",
		"background:rgba(22,93,255,.06);}",
		".pcc-delta-up{color:#e5484d;}",
		".pcc-delta-down{color:#00a870;}",
		".pcc-row-bar[data-up]{background:#e5484d;opacity:.12;}",
		".pcc-row-bar[data-down]{background:#00a870;opacity:.12;}",
		".pcc-more-btn{border:1px solid transparent;background:transparent;cursor:pointer;font-size:12px;",
		"color:var(--dsw-alias-state-business-primary,#165dff);padding:6px 8px;border-radius:8px;}",
		".pcc-more-btn:hover{background:var(--dsw-alias-interactive-bg-hover,#e8f3ff);}",
		".pcc-tabs{display:flex;gap:4px;margin:4px 0;padding:3px;border:1px solid var(--dsw-alias-border-l2,#e5e6eb);",
		"background:var(--dsw-alias-bg-base,#fff);border-radius:8px;}",
		".pcc-tab{flex:1;border:1px solid transparent;background:transparent;",
		"border-radius:6px;padding:6px 0;font-size:12px;cursor:pointer;",
		"color:var(--dsw-alias-label-primary,#1f2329);}",
		".pcc-tab[data-active]{border-color:rgba(22,93,255,.12);",
		"color:var(--dsw-alias-state-business-primary,#165dff);background:rgba(22,93,255,.08);font-weight:650;}",
		".pcc-pick{width:18px;height:18px;border-radius:50%;flex:none;cursor:pointer;padding:0;",
		"border:1.5px solid var(--dsw-alias-border-l2,#c9cdd4);background:transparent;",
		"color:#fff;font-size:10px;line-height:1;display:inline-flex;align-items:center;justify-content:center;}",
		".pcc-pick[data-on]{border-color:var(--dsw-alias-state-business-primary,#165dff);",
		"background:var(--dsw-alias-state-business-primary,#165dff);}",
		".pcc-tree-row{display:flex;align-items:center;gap:5px;padding:5px 7px 5px 0;border-radius:6px;",
		"font-size:12px;position:relative;overflow:hidden;margin-bottom:1px;cursor:pointer;}",
		".pcc-tree-row[data-leaf]{cursor:default;}",
		".pcc-tree-row:hover{background:var(--dsw-alias-interactive-bg-hover,#e8f3ff);}",
		".pcc-tree-toggle{appearance:none;-webkit-appearance:none;width:18px;height:20px;border:0;border-radius:5px;padding:0;background:transparent;",
		"color:var(--dsw-alias-label-tertiary,#86909c);flex:none;display:inline-flex;align-items:center;justify-content:center;",
		"line-height:0;cursor:pointer;transition:background .16s,color .16s,transform .16s;position:relative;}",
		".pcc-tree-toggle:hover{background:rgba(22,93,255,.05);color:var(--dsw-alias-state-business-primary,#165dff);}",
		".pcc-tree-toggle:focus-visible{outline:2px solid rgba(22,93,255,.4);outline-offset:1px;}",
		".pcc-tree-toggle svg{display:block;transition:transform .16s ease;}",
		".pcc-tree-toggle[data-open]{background:transparent;color:var(--dsw-alias-state-business-primary,#165dff);}",
		".pcc-tree-toggle[data-open] svg{transform:rotate(90deg);}",
		".pcc-tree-toggle-spacer{cursor:default;pointer-events:none;}",
		".pcc-tree-name{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;",
		"position:relative;}",
		".pcc-tree-meta{flex:none;color:var(--dsw-alias-label-tertiary,#86909c);position:relative;",
		"white-space:nowrap;font-size:11px;}",
		".pcc-tree-size{flex:none;font-weight:600;white-space:nowrap;position:relative;}",
		".pcc-tree-more{padding:3px 6px 3px 34px;font-size:11px;color:var(--dsw-alias-label-tertiary,#86909c);}",
		"@media(max-width:520px){.pcc-panel{min-width:320px;max-width:100vw;}.pcc-panel-body{padding:12px;}",
		".pcc-drive{grid-template-columns:minmax(72px,max-content) 1fr;}.pcc-drive-meta{grid-column:1/-1;}",
		".pcc-statrow{grid-template-columns:1fr;}}",
	].join("");
	document.head.appendChild(style);
}

export { injectCss };
